package com.tbc.demo.catalog.zip;

public interface TestString {

    String content = "<p style='text-align: right;'><span style='text-decoration: underline; color: rgb(255, 0, 0);'"
            + "><em><strong>Dear All,&nbsp;&nbsp;</strong></em></span></p><p><br/></p><p>近期Jerry Shih会来到AGS。"
            + "</p><p><br/></p><p>作为AGS的一员，请大家配合以下事项，让我们共同展现出AGS的专业风貌！</p><p><b"
            + "r/></p><p>时间：</p><p><br/></p><p>·&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;请按时上、下班，避免"
            + "迟到或早退。</p><p><br/></p><p>·&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;中午按时吃饭（12:00），"
            + "请不要提前。</p><p><br/></p><p>公共设施：</p><p><br/></p><p>·&nbsp; &nbsp; &nbsp; &nbsp; &n"
            + "bsp;中午请大家在就餐区吃午饭，请不要在会议室或座位上就餐。</p><p><br/></p><p>·&nbsp; &nbsp; &nbsp;"
            + " &nbsp; &nbsp;带饭的同仁请不要把饭盒放在吧台上，请放在冰箱。</p><p><br/></p><p>·&nbsp; &nbsp; &"
            + "nbsp; &nbsp; &nbsp;最后下班的同事请确认所有空调、灯等设备电源是否关闭。</p><p><br/></p><p st"
            + "yle='text-align: justify;'>·&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;VIP厕所请不要使用(哺乳期"
            + "员工除外)。</p><p><br/></p><p>仪表：</p><p><br/></p><p>·&nbsp; &nbsp; &nbsp; &nbsp; &nbs"
            + "p;着装需正式，颜色庄重、款式大方，请不要穿着休闲装。</p><p><br/></p><p>·&nbsp; &nbsp; &nbsp"
            + "; &nbsp; &nbsp;请避免大声喧哗。</p><p><br/></p><p>办公环境：</p><p><br/></p><p>·&nbsp; &nbsp"
            + "; &nbsp; &nbsp; &nbsp;请保证办公桌桌面的整洁。</p><p><br/></p><p>·&nbsp; &nbsp; &nbsp; &nbsp"
            + "; &nbsp;外套、围巾等服饰请挂在衣架或收进柜子里，请不要搭在椅背或放在桌面上。</p><p><br/></p><p>信息"
            + "安全：</p><p><br/></p><p>·&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;离开座位时请锁掉电脑。</p><p><br/>"
            + "</p><p>·&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;涉及保密信息的文件请不要放在桌面上。</p><p><br/></"
            + "p><p>·&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;请不要把信息留在白板上。</p><p><br/></p><p>HR &amp; A"
            + "dmin</p><p><br/></p><p>AMAX Global Services</p><p><br/></p>"
            + "<p style='text-align: right;'><span style='text-decoration: underline; color: rgb(255, 0, 0);'"
            + "><em><strong>Dear All,&nbsp;&nbsp;</strong></em></span></p><p><br/></p><p>近期Jerry Shih会来到AGS。"
            + "</p><p><br/></p><p>作为AGS的一员，请大家配合以下事项，让我们共同展现出AGS的专业风貌！</p><p><b"
            + "r/></p><p>时间：</p><p><br/></p><p>·&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;请按时上、下班，避免"
            + "迟到或早退。</p><p><br/></p><p>·&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;中午按时吃饭（12:00），"
            + "请不要提前。</p><p><br/></p><p>公共设施：</p><p><br/></p><p>·&nbsp; &nbsp; &nbsp; &nbsp; &n"
            + "bsp;中午请大家在就餐区吃午饭，请不要在会议室或座位上就餐。</p><p><br/></p><p>·&nbsp; &nbsp; &nbsp;"
            + " &nbsp; &nbsp;带饭的同仁请不要把饭盒放在吧台上，请放在冰箱。</p><p><br/></p><p>·&nbsp; &nbsp; &"
            + "nbsp; &nbsp; &nbsp;最后下班的同事请确认所有空调、灯等设备电源是否关闭。</p><p><br/></p><p st"
            + "yle='text-align: justify;'>·&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;VIP厕所请不要使用(哺乳期"
            + "员工除外)。</p><p><br/></p><p>仪表：</p><p><br/></p><p>·&nbsp; &nbsp; &nbsp; &nbsp; &nbs"
            + "p;着装需正式，颜色庄重、款式大方，请不要穿着休闲装。</p><p><br/></p><p>·&nbsp; &nbsp; &nbsp"
            + "; &nbsp; &nbsp;请避免大声喧哗。</p><p><br/></p><p>办公环境：</p><p><br/></p><p>·&nbsp; &nbsp"
            + "; &nbsp; &nbsp; &nbsp;请保证办公桌桌面的整洁。</p><p><br/></p><p>·&nbsp; &nbsp; &nbsp; &nbsp"
            + "; &nbsp;外套、围巾等服饰请挂在衣架或收进柜子里，请不要搭在椅背或放在桌面上。</p><p><br/></p><p>信息"
            + "安全：</p><p><br/></p><p>·&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;离开座位时请锁掉电脑。</p><p><br/>"
            + "</p><p>·&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;涉及保密信息的文件请不要放在桌面上。</p><p><br/></"
            + "p><p>·&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;请不要把信息留在白板上。</p><p><br/></p><p>HR &amp; A"
            + "dmin</p><p><br/></p><p>AMAX Global Services</p><p><br/></p>"
            + "><em><strong>Dear All,&nbsp;&nbsp;</strong></em></span></p><p><br/></p><p>近期Jerry Shih会来到AGS。"
            + "</p><p><br/></p><p>作为AGS的一员，请大家配合以下事项，让我们共同展现出AGS的专业风貌！</p><p><b"
            + "r/></p><p>时间：</p><p><br/></p><p>·&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;请按时上、下班，避免"
            + "迟到或早退。</p><p><br/></p><p>·&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;中午按时吃饭（12:00），"
            + "请不要提前。</p><p><br/></p><p>公共设施：</p><p><br/></p><p>·&nbsp; &nbsp; &nbsp; &nbsp; &n"
            + "bsp;中午请大家在就餐区吃午饭，请不要在会议室或座位上就餐。</p><p><br/></p><p>·&nbsp; &nbsp; &nbsp;"
            + " &nbsp; &nbsp;带饭的同仁请不要把饭盒放在吧台上，请放在冰箱。</p><p><br/></p><p>·&nbsp; &nbsp; &"
            + "nbsp; &nbsp; &nbsp;最后下班的同事请确认所有空调、灯等设备电源是否关闭。</p><p><br/></p><p st"
            + "yle='text-align: justify;'>·&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;VIP厕所请不要使用(哺乳期"
            + "员工除外)。</p><p><br/></p><p>仪表：</p><p><br/></p><p>·&nbsp; &nbsp; &nbsp; &nbsp; &nbs"
            + "p;着装需正式，颜色庄重、款式大方，请不要穿着休闲装。</p><p><br/></p><p>·&nbsp; &nbsp; &nbsp"
            + "; &nbsp; &nbsp;请避免大声喧哗。</p><p><br/></p><p>办公环境：</p><p><br/></p><p>·&nbsp; &nbsp"
            + "; &nbsp; &nbsp; &nbsp;请保证办公桌桌面的整洁。</p><p><br/></p><p>·&nbsp; &nbsp; &nbsp; &nbsp"
            + "; &nbsp;外套、围巾等服饰请挂在衣架或收进柜子里，请不要搭在椅背或放在桌面上。</p><p><br/></p><p>信息"
            + "安全：</p><p><br/></p><p>·&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;离开座位时请锁掉电脑。</p><p><br/>"
            + "</p><p>·&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;涉及保密信息的文件请不要放在桌面上。</p><p><br/></"
            + "p><p>·&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;请不要把信息留在白板上。</p><p><br/></p><p>HR &amp; A"
            + "dmin</p><p><br/></p><p>AMAX Global Services</p><p><br/></p>"
            + "<p style='text-align: right;'><span style='text-decoration: underline; color: rgb(255, 0, 0);'"
            + "><em><strong>Dear All,&nbsp;&nbsp;</strong></em></span></p><p><br/></p><p>近期Jerry Shih会来到AGS。"
            + "</p><p><br/></p><p>作为AGS的一员，请大家配合以下事项，让我们共同展现出AGS的专业风貌！</p><p><b"
            + "r/></p><p>时间：</p><p><br/></p><p>·&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;请按时上、下班，避免"
            + "迟到或早退。</p><p><br/></p><p>·&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;中午按时吃饭（12:00），"
            + "请不要提前。</p><p><br/></p><p>公共设施：</p><p><br/></p><p>·&nbsp; &nbsp; &nbsp; &nbsp; &n"
            + "bsp;中午请大家在就餐区吃午饭，请不要在会议室或座位上就餐。</p><p><br/></p><p>·&nbsp; &nbsp; &nbsp;"
            + " &nbsp; &nbsp;带饭的同仁请不要把饭盒放在吧台上，请放在冰箱。</p><p><br/></p><p>·&nbsp; &nbsp; &"
            + "nbsp; &nbsp; &nbsp;最后下班的同事请确认所有空调、灯等设备电源是否关闭。</p><p><br/></p><p st"
            + "yle='text-align: justify;'>·&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;VIP厕所请不要使用(哺乳期"
            + "员工除外)。</p><p><br/></p><p>仪表：</p><p><br/></p><p>·&nbsp; &nbsp; &nbsp; &nbsp; &nbs"
            + "p;着装需正式，颜色庄重、款式大方，请不要穿着休闲装。</p><p><br/></p><p>·&nbsp; &nbsp; &nbsp"
            + "; &nbsp; &nbsp;请避免大声喧哗。</p><p><br/></p><p>办公环境：</p><p><br/></p><p>·&nbsp; &nbsp"
            + "; &nbsp; &nbsp; &nbsp;请保证办公桌桌面的整洁。</p><p><br/></p><p>·&nbsp; &nbsp; &nbsp; &nbsp"
            + "; &nbsp;外套、围巾等服饰请挂在衣架或收进柜子里，请不要搭在椅背或放在桌面上。</p><p><br/></p><p>信息"
            + "安全：</p><p><br/></p><p>·&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;离开座位时请锁掉电脑。</p><p><br/>"
            + "</p><p>·&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;涉及保密信息的文件请不要放在桌面上。</p><p><br/></"
            + "p><p>·&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;请不要把信息留在白板上。</p><p><br/></p><p>HR &amp; A"
            + "dmin</p><p><br/></p><p>AMAX Global Services</p><p><br/></p>" + "><em><strong>Dear All,&nbsp;&nbsp;</strong></em></span></p><p><br/></p><p>近期Jerry Shih会来到AGS。"
            + "</p><p><br/></p><p>作为AGS的一员，请大家配合以下事项，让我们共同展现出AGS的专业风貌！</p><p><b"
            + "r/></p><p>时间：</p><p><br/></p><p>·&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;请按时上、下班，避免"
            + "迟到或早退。</p><p><br/></p><p>·&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;中午按时吃饭（12:00），"
            + "请不要提前。</p><p><br/></p><p>公共设施：</p><p><br/></p><p>·&nbsp; &nbsp; &nbsp; &nbsp; &n"
            + "bsp;中午请大家在就餐区吃午饭，请不要在会议室或座位上就餐。</p><p><br/></p><p>·&nbsp; &nbsp; &nbsp;"
            + " &nbsp; &nbsp;带饭的同仁请不要把饭盒放在吧台上，请放在冰箱。</p><p><br/></p><p>·&nbsp; &nbsp; &"
            + "nbsp; &nbsp; &nbsp;最后下班的同事请确认所有空调、灯等设备电源是否关闭。</p><p><br/></p><p st"
            + "yle='text-align: justify;'>·&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;VIP厕所请不要使用(哺乳期"
            + "员工除外)。</p><p><br/></p><p>仪表：</p><p><br/></p><p>·&nbsp; &nbsp; &nbsp; &nbsp; &nbs"
            + "p;着装需正式，颜色庄重、款式大方，请不要穿着休闲装。</p><p><br/></p><p>·&nbsp; &nbsp; &nbsp"
            + "; &nbsp; &nbsp;请避免大声喧哗。</p><p><br/></p><p>办公环境：</p><p><br/></p><p>·&nbsp; &nbsp"
            + "; &nbsp; &nbsp; &nbsp;请保证办公桌桌面的整洁。</p><p><br/></p><p>·&nbsp; &nbsp; &nbsp; &nbsp"
            + "; &nbsp;外套、围巾等服饰请挂在衣架或收进柜子里，请不要搭在椅背或放在桌面上。</p><p><br/></p><p>信息"
            + "安全：</p><p><br/></p><p>·&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;离开座位时请锁掉电脑。</p><p><br/>"
            + "</p><p>·&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;涉及保密信息的文件请不要放在桌面上。</p><p><br/></"
            + "p><p>·&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;请不要把信息留在白板上。</p><p><br/></p><p>HR &amp; A"
            + "dmin</p><p><br/></p><p>AMAX Global Services</p><p><br/></p>"
            + "<p style='text-align: right;'><span style='text-decoration: underline; color: rgb(255, 0, 0);'"
            + "><em><strong>Dear All,&nbsp;&nbsp;</strong></em></span></p><p><br/></p><p>近期Jerry Shih会来到AGS。"
            + "</p><p><br/></p><p>作为AGS的一员，请大家配合以下事项，让我们共同展现出AGS的专业风貌！</p><p><b"
            + "r/></p><p>时间：</p><p><br/></p><p>·&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;请按时上、下班，避免"
            + "迟到或早退。</p><p><br/></p><p>·&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;中午按时吃饭（12:00），"
            + "请不要提前。</p><p><br/></p><p>公共设施：</p><p><br/></p><p>·&nbsp; &nbsp; &nbsp; &nbsp; &n"
            + "bsp;中午请大家在就餐区吃午饭，请不要在会议室或座位上就餐。</p><p><br/></p><p>·&nbsp; &nbsp; &nbsp;"
            + " &nbsp; &nbsp;带饭的同仁请不要把饭盒放在吧台上，请放在冰箱。</p><p><br/></p><p>·&nbsp; &nbsp; &"
            + "nbsp; &nbsp; &nbsp;最后下班的同事请确认所有空调、灯等设备电源是否关闭。</p><p><br/></p><p st"
            + "yle='text-align: justify;'>·&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;VIP厕所请不要使用(哺乳期"
            + "员工除外)。</p><p><br/></p><p>仪表：</p><p><br/></p><p>·&nbsp; &nbsp; &nbsp; &nbsp; &nbs"
            + "p;着装需正式，颜色庄重、款式大方，请不要穿着休闲装。</p><p><br/></p><p>·&nbsp; &nbsp; &nbsp"
            + "; &nbsp; &nbsp;请避免大声喧哗。</p><p><br/></p><p>办公环境：</p><p><br/></p><p>·&nbsp; &nbsp"
            + "; &nbsp; &nbsp; &nbsp;请保证办公桌桌面的整洁。</p><p><br/></p><p>·&nbsp; &nbsp; &nbsp; &nbsp"
            + "; &nbsp;外套、围巾等服饰请挂在衣架或收进柜子里，请不要搭在椅背或放在桌面上。</p><p><br/></p><p>信息"
            + "安全：</p><p><br/></p><p>·&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;离开座位时请锁掉电脑。</p><p><br/>"
            + "</p><p>·&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;涉及保密信息的文件请不要放在桌面上。</p><p><br/></"
            + "p><p>·&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;请不要把信息留在白板上。</p><p><br/></p><p>HR &amp; A"
            + "dmin</p><p><br/></p><p>AMAX Global Services</p><p><br/></p>"
            + "><em><strong>Dear All,&nbsp;&nbsp;</strong></em></span></p><p><br/></p><p>近期Jerry Shih会来到AGS。"
            + "</p><p><br/></p><p>作为AGS的一员，请大家配合以下事项，让我们共同展现出AGS的专业风貌！</p><p><b"
            + "r/></p><p>时间：</p><p><br/></p><p>·&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;请按时上、下班，避免"
            + "迟到或早退。</p><p><br/></p><p>·&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;中午按时吃饭（12:00），"
            + "请不要提前。</p><p><br/></p><p>公共设施：</p><p><br/></p><p>·&nbsp; &nbsp; &nbsp; &nbsp; &n"
            + "bsp;中午请大家在就餐区吃午饭，请不要在会议室或座位上就餐。</p><p><br/></p><p>·&nbsp; &nbsp; &nbsp;"
            + " &nbsp; &nbsp;带饭的同仁请不要把饭盒放在吧台上，请放在冰箱。</p><p><br/></p><p>·&nbsp; &nbsp; &"
            + "nbsp; &nbsp; &nbsp;最后下班的同事请确认所有空调、灯等设备电源是否关闭。</p><p><br/></p><p st"
            + "yle='text-align: justify;'>·&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;VIP厕所请不要使用(哺乳期"
            + "员工除外)。</p><p><br/></p><p>仪表：</p><p><br/></p><p>·&nbsp; &nbsp; &nbsp; &nbsp; &nbs"
            + "p;着装需正式，颜色庄重、款式大方，请不要穿着休闲装。</p><p><br/></p><p>·&nbsp; &nbsp; &nbsp"
            + "; &nbsp; &nbsp;请避免大声喧哗。</p><p><br/></p><p>办公环境：</p><p><br/></p><p>·&nbsp; &nbsp"
            + "; &nbsp; &nbsp; &nbsp;请保证办公桌桌面的整洁。</p><p><br/></p><p>·&nbsp; &nbsp; &nbsp; &nbsp"
            + "; &nbsp;外套、围巾等服饰请挂在衣架或收进柜子里，请不要搭在椅背或放在桌面上。</p><p><br/></p><p>信息"
            + "安全：</p><p><br/></p><p>·&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;离开座位时请锁掉电脑。</p><p><br/>"
            + "</p><p>·&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;涉及保密信息的文件请不要放在桌面上。</p><p><br/></"
            + "p><p>·&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;请不要把信息留在白板上。</p><p><br/></p><p>HR &amp; A"
            + "dmin</p><p><br/></p><p>AMAX Global Services</p><p><br/></p>"
            + "<p style='text-align: right;'><span style='text-decoration: underline; color: rgb(255, 0, 0);'"
            + "><em><strong>Dear All,&nbsp;&nbsp;</strong></em></span></p><p><br/></p><p>近期Jerry Shih会来到AGS。"
            + "</p><p><br/></p><p>作为AGS的一员，请大家配合以下事项，让我们共同展现出AGS的专业风貌！</p><p><b"
            + "r/></p><p>时间：</p><p><br/></p><p>·&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;请按时上、下班，避免"
            + "迟到或早退。</p><p><br/></p><p>·&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;中午按时吃饭（12:00），"
            + "请不要提前。</p><p><br/></p><p>公共设施：</p><p><br/></p><p>·&nbsp; &nbsp; &nbsp; &nbsp; &n"
            + "bsp;中午请大家在就餐区吃午饭，请不要在会议室或座位上就餐。</p><p><br/></p><p>·&nbsp; &nbsp; &nbsp;"
            + " &nbsp; &nbsp;带饭的同仁请不要把饭盒放在吧台上，请放在冰箱。</p><p><br/></p><p>·&nbsp; &nbsp; &"
            + "nbsp; &nbsp; &nbsp;最后下班的同事请确认所有空调、灯等设备电源是否关闭。</p><p><br/></p><p st"
            + "yle='text-align: justify;'>·&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;VIP厕所请不要使用(哺乳期"
            + "员工除外)。</p><p><br/></p><p>仪表：</p><p><br/></p><p>·&nbsp; &nbsp; &nbsp; &nbsp; &nbs"
            + "p;着装需正式，颜色庄重、款式大方，请不要穿着休闲装。</p><p><br/></p><p>·&nbsp; &nbsp; &nbsp"
            + "; &nbsp; &nbsp;请避免大声喧哗。</p><p><br/></p><p>办公环境：</p><p><br/></p><p>·&nbsp; &nbsp"
            + "; &nbsp; &nbsp; &nbsp;请保证办公桌桌面的整洁。</p><p><br/></p><p>·&nbsp; &nbsp; &nbsp; &nbsp"
            + "; &nbsp;外套、围巾等服饰请挂在衣架或收进柜子里，请不要搭在椅背或放在桌面上。</p><p><br/></p><p>信息"
            + "安全：</p><p><br/></p><p>·&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;离开座位时请锁掉电脑。</p><p><br/>"
            + "</p><p>·&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;涉及保密信息的文件请不要放在桌面上。</p><p><br/></"
            + "p><p>·&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;请不要把信息留在白板上。</p><p><br/></p><p>HR &amp; A"
            + "dmin</p><p><br/></p><p>AMAX Global Services</p><p><br/></p>";

}
